# -*- coding: utf-8 -*-
"""200901007 assignment 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b_k9fzD2SV7cFf3g5blkcaWDxua4re36
"""

import threading
input_str = ""                                             # Global variable

def input_thread():
  global input_str
  try:
    
    input_str = input("*****Input a string*****: ")     # INPUT THREAD
  except Exception as e:
    print(e)
    return

def reverse_thread():                                # REVERSE THREAD
  global input_str
  try:
    
    print(input_str[::-1])                               
  except Exception as e:
    print(e)
    return

def capital_thread():                               # CAPITAL THREAD
  global input_str
  try:
  
    print(input_str.upper() )
  except Exception as e:
    print(e ("\n \n"))
    return

def shift_thread():                              # SHIFT THREAD
  global input_str
  try:
    
    shifted_str = ""
    for ch in input_str:
      shifted_str += chr(ord(ch) + 2)
    print(shifted_str)
  except Exception as e:
    print(e)
    return

input_t = threading.Thread(target=input_thread)
reverse_t = threading.Thread(target=reverse_thread)
capital_t = threading.Thread(target=capital_thread)
shift_t = threading.Thread(target=shift_thread)

input_t.start()                                           # START INPUT THREAD                     
input_t.join()                                            # WAIT INPUT THREAD
reverse_t.start()                                         # START REVERSE THREAD
capital_t.start()                                         # START CAPITAL THREAD
shift_t.start()                                           # START SHIFT THREAD

reverse_t.join()                                         # WAIT REVERSE THREAD
capital_t.join()                                         # WAIT CAPITAL THREAD
shift_t.join()                                           # START SHIFT THREAD